#!/usr/bin/env bash
set -uo pipefail
ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"; FIXTURES="$ROOT/tests/fixtures/rubric-compiler/structure"
TMP_ROOT="$(mktemp -d "${TMPDIR:-/tmp}/gentle-ai-rubric-structure.XXXXXX")"; trap 'rm -rf -- "$TMP_ROOT"' EXIT
PASS=0; FAIL=0
put() { mkdir -p "$(dirname -- "$1")"; printf '%s\n' "$2" > "$1"; }
scalar() { < "$1" tr -d '\n'; }
ident() { local d="$1" k="$2" sum bytes; put "$d/kind" "$k"; put "$d/identity" "$3"; read -r sum bytes _ < <(cksum "$d/identity"); put "$d/id" "v1:$k:$sum:$bytes"; }
list() { local d="$1" n=0 x; shift; mkdir -p "$d"; for x; do put "$d/$(printf '%03d' "$n")" "$x"; n=$((n + 1)); done; }
fp() { (cd "$1" && find . -type f ! -name id ! -name identity ! -name fingerprint -print | LC_ALL=C sort | while IFS= read -r f; do printf '%s ' "$f"; cksum "$f"; done) | cksum | awk '{print $1 ":" $2}'; }
fps() { local b="$1" d f; shift; for f; do for d in "$b/facts"/*; do [ "$(scalar "$d/id")" = "$f" ] && printf '%s:%s\n' "$f" "$(fp "$d")"; done; done | cksum | awk '{print $1 ":" $2}'; }
extract() { awk '/^<!-- shape:details -->$/{s=1;next}/^<!-- \/shape:details -->$/{exit}s&&/^<!-- rubric-validator:start -->$/{b=1;next}s&&/^<!-- rubric-validator:end -->$/{exit}s&&b{print}' "$ROOT/deltas/sdd-init-rubric.md" > "$TMP_ROOT/validator"; chmod +x "$TMP_ROOT/validator"; }
bundle() {
  local b="$1" r oid gid f1 f2 aid bid sid did qid rid; r="$b/repository"
  mkdir -p "$r/work" "$r/tests" "$b"/{observations,facts,attestations,bindings,rows,questions,reinit,record-order}
  cp "$FIXTURES/repository/README.md" "$r/README.md"
  printf 'touch %q\n' "$TMP_ROOT/candidate-ran" > "$r/candidate-command"; chmod +x "$r/candidate-command"
  put "$b/schema" v1; put "$b/candidate-schema" v1; put "$b/root" "$r"; put "$b/resolution/matching" all-rows; put "$b/resolution/mode" strictest-wins; put "$b/resolution/default" unmatched-only
  ident "$b/observations/file" observation file; put "$b/observations/file/channel" file; put "$b/observations/file/locator" README.md; put "$b/observations/file/checksum" "$(cksum "$r/README.md" | awk '{print $1 " " $2}')"; put "$b/observations/file/source" fixture; put "$b/observations/file/provenance" observed; oid="$(scalar "$b/observations/file/id")"
  ident "$b/observations/graph" observation graph; put "$b/observations/graph/channel" codegraph; put "$b/observations/graph/status" untrusted; put "$b/observations/graph/scope" scope-only; put "$b/observations/graph/query" symbols; put "$b/observations/graph/index-revision" v1; put "$b/observations/graph/symbol" README; put "$b/observations/graph/repo-path" README.md; put "$b/observations/graph/source" fixture; put "$b/observations/graph/provenance" observed; gid="$(scalar "$b/observations/graph/id")"
  for rid in declaration tool; do ident "$b/facts/$rid" fact "$rid"; put "$b/facts/$rid/status" known; put "$b/facts/$rid/source" fixture; put "$b/facts/$rid/provenance" observed; put "$b/facts/$rid/source-path" README.md; put "$b/facts/$rid/evidence-kind" declaration; put "$b/facts/$rid/adapter" structural; list "$b/facts/$rid/observation-refs" "$oid"; put "$b/facts/$rid/fingerprint" "$(fp "$b/facts/$rid")"; done
  f1="$(scalar "$b/facts/declaration/id")"; f2="$(scalar "$b/facts/tool/id")"
  ident "$b/attestations/record" attestation record; aid="$(scalar "$b/attestations/record/id")"; put "$b/attestations/record/schema" v1; put "$b/attestations/record/attestation-id" "$aid"; for rid in adapter-id adapter-version adapter-bytes-digest input-digest status claim-kind executable method scope; do put "$b/attestations/record/$rid" structural; done; put "$b/attestations/record/source-locator" README.md; put "$b/attestations/record/observation-id" "$oid"
  ident "$b/bindings/unit" binding unit; bid="$(scalar "$b/bindings/unit/id")"; put "$b/bindings/unit/method" unit; put "$b/bindings/unit/scope" fixture; put "$b/bindings/unit/signature-coverage" tests; put "$b/bindings/unit/context/root" "$r"; put "$b/bindings/unit/context/workdir" work; put "$b/bindings/unit/context/executable" candidate-command; list "$b/bindings/unit/context/argv" candidate-command; list "$b/bindings/unit/platforms" shell; list "$b/bindings/unit/env"; list "$b/bindings/unit/requirements"; list "$b/bindings/unit/fact-refs" "$f1" "$f2"; put "$b/bindings/unit/declaration-ref" "$f1"; put "$b/bindings/unit/tool-proof-ref" "$f2"; list "$b/bindings/unit/attestation-refs" "$aid"
  ident "$b/rows/source" row source; sid="$(scalar "$b/rows/source/id")"; put "$b/rows/source/signature" source-change; put "$b/rows/source/mode" standard; put "$b/rows/source/state" pending; put "$b/rows/source/source" generated; put "$b/rows/source/selection" specific; put "$b/rows/source/trigger-kind" path; list "$b/rows/source/trigger-paths" tests; list "$b/rows/source/fact-refs" "$f1" "$f2"; put "$b/rows/source/fact-fingerprint" "$(fps "$b" "$f1" "$f2")"; list "$b/rows/source/disciplines" unit; list "$b/rows/source/binding-refs" "$bid"; list "$b/rows/source/attestation-refs" "$aid"
  ident "$b/rows/default" row default; did="$(scalar "$b/rows/default/id")"; put "$b/rows/default/signature" default; put "$b/rows/default/mode" skip; put "$b/rows/default/state" confirmed; put "$b/rows/default/source" generated; put "$b/rows/default/selection" unmatched-only; put "$b/rows/default/trigger-kind" unmatched; list "$b/rows/default/trigger-paths"; list "$b/rows/default/fact-refs" "$f1"; put "$b/rows/default/fact-fingerprint" "$(fps "$b" "$f1")"; list "$b/rows/default/disciplines"; list "$b/rows/default/binding-refs"; list "$b/rows/default/attestation-refs"; put "$b/rows/default/confirmation-answer" yes; put "$b/rows/default/confirmer" fixture
  ident "$b/questions/source" question source; qid="$(scalar "$b/questions/source/id")"; put "$b/questions/source/prompt" confirm; put "$b/questions/source/blocking" true; put "$b/questions/source/state" open; put "$b/questions/source/row-ref" "$sid"; list "$b/questions/source/fact-refs" "$f1"; list "$b/questions/source/allowed-answers" yes no
  put "$b/reinit/source/row-ref" "$did"; put "$b/reinit/source/prior-fingerprint" "$(fps "$b" "$f1")"; put "$b/reinit/source/state" preserved
  mapfile -t ids < <(printf '%s\n' "$oid" "$gid" "$f1" "$f2" "$aid" "$bid" "$sid" "$did" "$qid" | LC_ALL=C sort); list "$b/record-order" "${ids[@]}"; }
accept() { "$TMP_ROOT/validator" "$1" > "$2" 2> "$TMP_ROOT/error"; }; reject() { local name="$1" b="$2"; if accept "$b" "$TMP_ROOT/$name.out"; then printf 'FAIL: %s was accepted\n' "$name" >&2; FAIL=$((FAIL + 1)); else printf 'PASS: %s\n' "$name"; PASS=$((PASS + 1)); fi; }
extract; BASE="$TMP_ROOT/valid"; bundle "$BASE"
if accept "$BASE" "$TMP_ROOT/one.out" && accept "$BASE" "$TMP_ROOT/two.out" && cmp -s "$TMP_ROOT/one.out" "$TMP_ROOT/two.out" && grep -Fxq 'structure-valid/pending' "$TMP_ROOT/one.out" && [ ! -e "$TMP_ROOT/candidate-ran" ]; then printf 'PASS: valid deterministic non-executing bundle\n'; PASS=$((PASS + 1)); else cat "$TMP_ROOT/error" >&2; printf 'FAIL: valid deterministic non-executing bundle\n' >&2; FAIL=$((FAIL + 1)); fi
cp -a "$BASE" "$TMP_ROOT/root-workdir"; put "$TMP_ROOT/root-workdir/root" "$TMP_ROOT/root-workdir/repository"; put "$TMP_ROOT/root-workdir/bindings/unit/context/root" "$TMP_ROOT/root-workdir/repository"; put "$TMP_ROOT/root-workdir/bindings/unit/context/workdir" .
if accept "$TMP_ROOT/root-workdir" "$TMP_ROOT/root-one.out" && accept "$TMP_ROOT/root-workdir" "$TMP_ROOT/root-two.out" && cmp -s "$TMP_ROOT/root-one.out" "$TMP_ROOT/root-two.out" && grep -Fxq 'structure-valid/pending' "$TMP_ROOT/root-one.out" && [ ! -e "$TMP_ROOT/candidate-ran" ]; then printf 'PASS: root binding workdir is deterministic and non-executing\n'; PASS=$((PASS + 1)); else cat "$TMP_ROOT/error" >&2; printf 'FAIL: root binding workdir was rejected or executed\n' >&2; FAIL=$((FAIL + 1)); fi
  for name in multiline dangling provider binding-provider missing-attestation strict-missing-attestation missing-binding unresolved-binding-id missing-workdir missing-command-context invalid-state invalid-default-mode skip-unbound traversal glob symlink root-symlink parent-symlink bad-default bad-question bad-fingerprint bad-id bad-checksum duplicate-id reordered-order incomplete-codegraph missing-observation scalar-valid scalar-missing scalar-dangling row-fact-unlinked row-attestation-unlinked equal-refs unlinked preserved-mismatch stale-reinit stale-no-question; do cp -a "$BASE" "$TMP_ROOT/$name"; put "$TMP_ROOT/$name/root" "$TMP_ROOT/$name/repository"; put "$TMP_ROOT/$name/bindings/unit/context/root" "$TMP_ROOT/$name/repository"; done
printf 'two\nlines\n' > "$TMP_ROOT/multiline/observations/file/source"; reject multiline "$TMP_ROOT/multiline"
put "$TMP_ROOT/dangling/bindings/unit/declaration-ref" v1:fact:0:0; reject dangling "$TMP_ROOT/dangling"
  put "$TMP_ROOT/provider/facts/tool/provider" true; reject provider "$TMP_ROOT/provider"
  put "$TMP_ROOT/binding-provider/bindings/unit/provider" true; reject binding-provider "$TMP_ROOT/binding-provider"
  rm -f "$TMP_ROOT/missing-attestation/rows/source/attestation-refs/000"; reject missing-attestation "$TMP_ROOT/missing-attestation"
  put "$TMP_ROOT/strict-missing-attestation/rows/source/mode" strict-tdd; rm -f "$TMP_ROOT/strict-missing-attestation/rows/source/attestation-refs/000"; reject strict-missing-attestation "$TMP_ROOT/strict-missing-attestation"
  rm -f "$TMP_ROOT/missing-binding/rows/source/binding-refs/000"; reject missing-binding "$TMP_ROOT/missing-binding"
  put "$TMP_ROOT/unresolved-binding-id/rows/source/binding-refs/000" v1:binding:0:0; reject unresolved-binding-id "$TMP_ROOT/unresolved-binding-id"
  rm -f "$TMP_ROOT/missing-workdir/bindings/unit/context/workdir"; reject missing-workdir "$TMP_ROOT/missing-workdir"
  rm -f "$TMP_ROOT/missing-command-context/bindings/unit/context/executable"; reject missing-command-context "$TMP_ROOT/missing-command-context"
  put "$TMP_ROOT/invalid-state/rows/source/state" invalid; reject invalid-state "$TMP_ROOT/invalid-state"
  put "$TMP_ROOT/invalid-default-mode/rows/default/mode" pending; reject invalid-default-mode "$TMP_ROOT/invalid-default-mode"
  put "$TMP_ROOT/skip-unbound/rows/source/mode" skip; rm -f "$TMP_ROOT/skip-unbound/rows/source"/{binding,attestation}-refs/000; if accept "$TMP_ROOT/skip-unbound" "$TMP_ROOT/skip.out"; then printf 'PASS: skip-unbound\n'; PASS=$((PASS + 1)); else printf 'FAIL: skip-unbound was rejected\n' >&2; FAIL=$((FAIL + 1)); fi
   put "$TMP_ROOT/traversal/bindings/unit/context/workdir" ../; reject traversal "$TMP_ROOT/traversal"
  put "$TMP_ROOT/traversal/bindings/unit/context/workdir" ..; reject traversal "$TMP_ROOT/traversal"
  put "$TMP_ROOT/traversal/bindings/unit/context/workdir" /tmp; reject traversal "$TMP_ROOT/traversal"
   put "$TMP_ROOT/glob/bindings/unit/context/workdir" 'te*'; reject glob "$TMP_ROOT/glob"
  mkdir "$TMP_ROOT/symlink/repository/real"; cp "$TMP_ROOT/symlink/repository/README.md" "$TMP_ROOT/symlink/repository/real/inside"; ln -s real "$TMP_ROOT/symlink/repository/link"; put "$TMP_ROOT/symlink/observations/file/locator" link/inside; reject symlink "$TMP_ROOT/symlink"
  mv "$TMP_ROOT/root-symlink/repository" "$TMP_ROOT/root-symlink/real"; ln -s real "$TMP_ROOT/root-symlink/repository"; reject root-symlink "$TMP_ROOT/root-symlink"
   mkdir "$TMP_ROOT/parent-symlink/real"; mv "$TMP_ROOT/parent-symlink/repository" "$TMP_ROOT/parent-symlink/real/repository"; ln -s real "$TMP_ROOT/parent-symlink/parent"; put "$TMP_ROOT/parent-symlink/root" "$TMP_ROOT/parent-symlink/parent/repository"; reject parent-symlink "$TMP_ROOT/parent-symlink"
  cp -a "$BASE" "$TMP_ROOT/workdir-symlink"; put "$TMP_ROOT/workdir-symlink/root" "$TMP_ROOT/workdir-symlink/repository"; put "$TMP_ROOT/workdir-symlink/bindings/unit/context/root" "$TMP_ROOT/workdir-symlink/repository"; ln -s work "$TMP_ROOT/workdir-symlink/repository/link"; put "$TMP_ROOT/workdir-symlink/bindings/unit/context/workdir" link; reject workdir-symlink "$TMP_ROOT/workdir-symlink"
  cp -a "$BASE" "$TMP_ROOT/locator-root"; put "$TMP_ROOT/locator-root/root" "$TMP_ROOT/locator-root/repository"; put "$TMP_ROOT/locator-root/bindings/unit/context/root" "$TMP_ROOT/locator-root/repository"; put "$TMP_ROOT/locator-root/observations/file/locator" .; reject locator-root "$TMP_ROOT/locator-root"
put "$TMP_ROOT/bad-default/rows/default/trigger-kind" path; reject bad-default "$TMP_ROOT/bad-default"
put "$TMP_ROOT/bad-question/questions/source/row-ref" v1:row:0:0; reject bad-question "$TMP_ROOT/bad-question"
  put "$TMP_ROOT/bad-fingerprint/facts/tool/source" changed; reject bad-fingerprint "$TMP_ROOT/bad-fingerprint"
  put "$TMP_ROOT/bad-id/facts/tool/id" bad; reject bad-id "$TMP_ROOT/bad-id"
  put "$TMP_ROOT/bad-checksum/observations/file/checksum" '0 0'; reject bad-checksum "$TMP_ROOT/bad-checksum"
  ident "$TMP_ROOT/duplicate-id/facts/tool" fact declaration; reject duplicate-id "$TMP_ROOT/duplicate-id"
  a="$(scalar "$TMP_ROOT/reordered-order/record-order/000")"; z="$(scalar "$TMP_ROOT/reordered-order/record-order/001")"; put "$TMP_ROOT/reordered-order/record-order/000" "$z"; put "$TMP_ROOT/reordered-order/record-order/001" "$a"; reject reordered-order "$TMP_ROOT/reordered-order"
  rm -f "$TMP_ROOT/incomplete-codegraph/observations/graph/symbol"; reject incomplete-codegraph "$TMP_ROOT/incomplete-codegraph"
  rm -f "$TMP_ROOT/missing-observation/facts/tool/observation-refs/000"; reject missing-observation "$TMP_ROOT/missing-observation"
  if accept "$TMP_ROOT/scalar-valid" "$TMP_ROOT/scalar.out"; then printf 'PASS: scalar-valid\n'; PASS=$((PASS + 1)); else printf 'FAIL: scalar-valid was rejected\n' >&2; FAIL=$((FAIL + 1)); fi
  rm -f "$TMP_ROOT/scalar-missing/attestations/record/observation-id"; reject scalar-missing "$TMP_ROOT/scalar-missing"
  put "$TMP_ROOT/scalar-dangling/attestations/record/observation-id" v1:observation:0:0; reject scalar-dangling "$TMP_ROOT/scalar-dangling"
  rm -f "$TMP_ROOT/row-fact-unlinked/rows/source/fact-refs/001"; put "$TMP_ROOT/row-fact-unlinked/rows/source/fact-fingerprint" "$(fps "$TMP_ROOT/row-fact-unlinked" "$(scalar "$TMP_ROOT/row-fact-unlinked/facts/declaration/id")")"; reject row-fact-unlinked "$TMP_ROOT/row-fact-unlinked"
  rm -f "$TMP_ROOT/row-attestation-unlinked/bindings/unit/attestation-refs/000"; reject row-attestation-unlinked "$TMP_ROOT/row-attestation-unlinked"
put "$TMP_ROOT/equal-refs/bindings/unit/tool-proof-ref" "$(scalar "$TMP_ROOT/equal-refs/bindings/unit/declaration-ref")"; reject equal-refs "$TMP_ROOT/equal-refs"
rm -f "$TMP_ROOT/unlinked/bindings/unit/fact-refs/001"; reject unlinked "$TMP_ROOT/unlinked"
put "$TMP_ROOT/preserved-mismatch/reinit/source/prior-fingerprint" mismatch; reject preserved-mismatch "$TMP_ROOT/preserved-mismatch"
put "$TMP_ROOT/stale-reinit/reinit/source/row-ref" "$(scalar "$TMP_ROOT/stale-reinit/rows/source/id")"; put "$TMP_ROOT/stale-reinit/reinit/source/prior-fingerprint" mismatch; put "$TMP_ROOT/stale-reinit/reinit/source/state" stale; put "$TMP_ROOT/stale-reinit/rows/source/state" stale; if accept "$TMP_ROOT/stale-reinit" "$TMP_ROOT/stale.out"; then printf 'PASS: stale-reinit\n'; PASS=$((PASS + 1)); else printf 'FAIL: stale-reinit was rejected\n' >&2; FAIL=$((FAIL + 1)); fi
put "$TMP_ROOT/stale-no-question/reinit/source/row-ref" "$(scalar "$TMP_ROOT/stale-no-question/rows/source/id")"; put "$TMP_ROOT/stale-no-question/reinit/source/prior-fingerprint" mismatch; put "$TMP_ROOT/stale-no-question/reinit/source/state" stale; put "$TMP_ROOT/stale-no-question/rows/source/state" stale; rm -rf "$TMP_ROOT/stale-no-question/questions/source"; reject stale-no-question "$TMP_ROOT/stale-no-question"
printf '\n%d passed, %d failed\n' "$PASS" "$FAIL"; [ "$FAIL" -eq 0 ]
