#!/usr/bin/env bash
set -uo pipefail
ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"; TMP="$(mktemp -d "${TMPDIR:-/tmp}/gentle-ai-rubric-gate.XXXXXX")"; trap 'rm -rf -- "$TMP"' EXIT; PASS=0; FAIL=0
put() { mkdir -p "$(dirname -- "$1")"; printf '%s\n' "$2" > "$1"; }; get() { tr -d '\n' < "$1"; }
ok() { printf 'PASS: %s\n' "$1"; PASS=$((PASS + 1)); }; no() { printf 'FAIL: %s\n' "$1" >&2; FAIL=$((FAIL + 1)); }
reject() { "$@" >/dev/null 2>&1; }
extract_block() { awk -v s="$1" -v n="$2" '$0 == ("<!-- shape:" s " -->") {a=1;next} $0 == ("<!-- /shape:" s " -->") {exit} a && $0 == ("<!-- rubric-" n ":start -->") {b=1;next} a && $0 == ("<!-- rubric-" n ":end -->") {exit} b {print}' "$ROOT/deltas/sdd-init-rubric.md" > "$3"; chmod +x "$3"; }
payload() { awk '/^  cat > "\$validator" <<\x27EOF\x27$/{p=1;next} p && /^EOF$/{exit} p{print}' "$1" > "$2"; }
load_structure_fixture() {
  export FIXTURES="$ROOT/tests/fixtures/rubric-compiler/structure" TMP_ROOT="$TMP"
  # shellcheck disable=SC1090
  source <(awk 'NR >= 6 && NR <= 29 {print}' "$ROOT/tests/rubric-compiler-structure.sh")
}
sync_facts() { local b=$1 d p; put "$b/facts/declaration/fingerprint" "$(fp "$b/facts/declaration")"; put "$b/facts/tool/fingerprint" "$(fp "$b/facts/tool")"; d="$(get "$b/facts/declaration/id")"; p="$(get "$b/facts/tool/id")"; put "$b/rows/source/fact-fingerprint" "$(fps "$b" "$d" "$p")"; put "$b/rows/default/fact-fingerprint" "$(fps "$b" "$d")"; put "$b/reinit/source/prior-fingerprint" "$(fps "$b" "$d")"; }
rebase_root() { put "$1/root" "$1/repository"; put "$1/bindings/unit/context/root" "$1/repository"; }
bundle_cnsic() {
  local b=$1 r; bundle "$b"; r="$b/repository"; cp -a "$ROOT/tests/fixtures/rubric-compiler/adapters/." "$r/"
  put "$b/observations/file/locator" AGENTS.md; put "$b/observations/file/checksum" "$(cksum "$r/AGENTS.md" | awk '{print $1 " " $2}')"
  put "$b/observations/graph/channel" file; put "$b/observations/graph/locator" requirements.txt; put "$b/observations/graph/checksum" "$(cksum "$r/requirements.txt" | awk '{print $1 " " $2}')"
  put "$b/facts/declaration/adapter" cnsic-python-v1; put "$b/facts/declaration/evidence-kind" command-declaration; put "$b/facts/tool/adapter" cnsic-python-v1; put "$b/facts/tool/evidence-kind" tool-proof; list "$b/facts/tool/observation-refs" "$(get "$b/observations/graph/id")"
  put "$b/bindings/unit/context/executable" python; put "$b/bindings/unit/context/workdir" .; put "$b/bindings/unit/method" unit; put "$b/bindings/unit/scope" path-prefix:tests/unit; put "$b/bindings/unit/signature-coverage" tests/unit; list "$b/bindings/unit/context/argv" -m pytest tests/unit/ -n auto -q; list "$b/bindings/unit/context/env"; sync_facts "$b"
}
bundle_gentle() { bundle_cnsic "$1"; local r="$1/repository"; put "$1/observations/file/locator" CONTRIBUTING.md; put "$1/observations/file/checksum" "$(cksum "$r/CONTRIBUTING.md" | awk '{print $1 " " $2}')"; put "$1/observations/graph/locator" go.mod; put "$1/observations/graph/checksum" "$(cksum "$r/go.mod" | awk '{print $1 " " $2}')"; put "$1/facts/declaration/adapter" gentle-ai-go-v1; put "$1/facts/tool/adapter" gentle-ai-go-v1; put "$1/bindings/unit/context/executable" go; put "$1/bindings/unit/scope" module-root; put "$1/bindings/unit/signature-coverage" .; list "$1/bindings/unit/context/argv" test ./...; sync_facts "$1"; }
 tamper_fields() { local copy=$1; shift; local field; for field; do put "$copy/records/000/$field" replay; done; }
attestation_identity() { local d=$1 k; for k in adapter-bytes-digest adapter-id adapter-version argv-digest binding-id claim-kind evidence-fact-id executable input-digest method observation-digest observation-id schema scope source-locator status; do printf '%s=%s\n' "$k" "$(get "$d/$k")"; done; }
refresh_order() { local b=$1 g d; local -a ids=(); for g in observations facts attestations bindings rows questions; do for d in "$b/$g"/*; do [ -d "$d" ] && ids+=("$(get "$d/id")"); done; done; mapfile -t ids < <(printf '%s\n' "${ids[@]}" | LC_ALL=C sort); list "$b/record-order" "${ids[@]}"; }
write_cp_hook() {
  mkdir -p "$TMP/hook-bin"
  cat > "$TMP/hook-bin/cp" <<'EOF'
#!/bin/sh
for x; do
  [ "${DRIFT_META-}" = "$x" ] && { /bin/cp "$@"; printf drift > "$DRIFT_META_FILE"; : > "$DRIFT_META_MARK"; exit; }
  [ "${DRIFT_RECORDS-}" = "$x" ] && { /bin/cp "$@"; printf drift > "$DRIFT_RECORD_FILE"; : > "$DRIFT_RECORDS_MARK"; exit; }
  [ "${DRIFT_EVIDENCE-}" = "$x" ] && { /bin/cp "$@"; printf drift >> "$DRIFT_EVIDENCE"; : > "$DRIFT_EVIDENCE_MARK"; exit; }
done
exec /bin/cp "$@"
EOF
  chmod +x "$TMP/hook-bin/cp"
}
load_structure_fixture; extract_block details adapter-gate "$TMP/details"; extract_block pi adapter-gate "$TMP/pi"; extract_block details adapter-records "$TMP/records-run"; extract_block details validator "$TMP/validator"; payload "$TMP/details" "$TMP/details-payload"; payload "$TMP/pi" "$TMP/pi-payload"
cmp -s "$TMP/details" "$TMP/pi" && [ -s "$TMP/details" ] && ok 'Details and Pi gate bytes match' || no 'missing or divergent gate'
cmp -s "$TMP/validator" "$TMP/details-payload" && cmp -s "$TMP/validator" "$TMP/pi-payload" && ok 'embedded Unit1A payloads have byte parity' || no 'embedded Unit1A payload drift'
b="$TMP/base"; bundle_cnsic "$b"; REC="$TMP/records"; "$TMP/validator" "$b" >/dev/null && "$TMP/records-run" records "$b" "$REC" || { no 'valid detached CNSIC fixture'; exit 1; }; RUN="$TMP/details"; OUT="$TMP/semantic-receipt"
if "$RUN" gate "$b" "$REC" "$OUT" && grep -Fxq 'semantic-valid/pending' "$OUT" && [ ! -d "$OUT" ]; then ok 'correct CNSIC semantic replay returns only receipt'; else no 'correct CNSIC semantic replay'; fi
cp -a "$b" "$TMP/workdir-drift"; put "$TMP/workdir-drift/bindings/unit/context/workdir" work; ! reject "$RUN" gate "$TMP/workdir-drift" "$REC" "$TMP/workdir-drift-out" && ok 'workdir drift blocks replay independently' || no 'workdir drift was accepted'
cp -a "$b" "$TMP/env-drift"; list "$TMP/env-drift/bindings/unit/context/env" SAFE=1; ! reject "$RUN" gate "$TMP/env-drift" "$REC" "$TMP/env-drift-out" && ok 'non-empty env blocks replay independently' || no 'non-empty env was accepted'
ln -s "$b" "$TMP/candidate-symlink"; ! reject "$RUN" gate "$TMP/candidate-symlink" "$REC" "$TMP/candidate-symlink-out" && ok 'symlinked candidate directory blocks replay' || no 'symlinked candidate directory was accepted'
mkdir "$TMP/candidate-real"; cp -a "$b" "$TMP/candidate-real/bundle"; ln -s "$TMP/candidate-real" "$TMP/candidate-parent"; ! reject "$RUN" gate "$TMP/candidate-parent/bundle" "$REC" "$TMP/candidate-parent-out" && ok 'symlinked candidate path component blocks replay' || no 'symlinked candidate path component was accepted'
cp -a "$b" "$TMP/root-symlink"; rebase_root "$TMP/root-symlink"; mv "$TMP/root-symlink/repository" "$TMP/root-symlink/real"; ln -s real "$TMP/root-symlink/repository"; ! reject "$RUN" gate "$TMP/root-symlink" "$REC" "$TMP/root-symlink-out" && ok 'symlinked repository root blocks replay' || no 'symlinked repository root was accepted'
cp -a "$b" "$TMP/locator-symlink"; rebase_root "$TMP/locator-symlink"; mkdir "$TMP/locator-symlink/repository/real"; mv "$TMP/locator-symlink/repository/AGENTS.md" "$TMP/locator-symlink/repository/real/AGENTS.md"; ln -s real "$TMP/locator-symlink/repository/link"; put "$TMP/locator-symlink/observations/file/locator" link/AGENTS.md; put "$TMP/locator-symlink/observations/file/checksum" "$(cksum "$TMP/locator-symlink/repository/real/AGENTS.md" | awk '{print $1 " " $2}')"; sync_facts "$TMP/locator-symlink"; ! reject "$RUN" gate "$TMP/locator-symlink" "$REC" "$TMP/locator-symlink-out" && ok 'symlinked evidence locator blocks replay' || no 'symlinked evidence locator was accepted'
ln -s "$REC" "$TMP/records-symlink"; ! reject "$RUN" gate "$b" "$TMP/records-symlink" "$TMP/records-symlink-out" && ok 'symlinked detached set blocks replay' || no 'symlinked detached set was accepted'
cp -a "$REC" "$TMP/records-intermediate"; mv "$TMP/records-intermediate/records" "$TMP/records-intermediate/real"; ln -s real "$TMP/records-intermediate/records"; ! reject "$RUN" gate "$b" "$TMP/records-intermediate" "$TMP/records-intermediate-out" && ok 'symlinked detached records directory blocks replay' || no 'symlinked detached records directory was accepted'
write_cp_hook; cp -a "$b" "$TMP/snapshot-drift"; cp -a "$REC" "$TMP/snapshot-records"; DRIFT_META="$TMP/snapshot-drift/bindings" DRIFT_META_FILE="$TMP/snapshot-drift/bindings/unit/context/workdir" DRIFT_META_MARK="$TMP/meta-mutated" DRIFT_RECORDS="$TMP/snapshot-records/records" DRIFT_RECORD_FILE="$TMP/snapshot-records/records/000/adapter-id" DRIFT_RECORDS_MARK="$TMP/records-mutated" PATH="$TMP/hook-bin:$PATH" "$RUN" gate "$TMP/snapshot-drift" "$TMP/snapshot-records" "$TMP/snapshot-drift-out" && [ -e "$TMP/meta-mutated" ] && [ -e "$TMP/records-mutated" ] && grep -Fxq 'semantic-valid/pending' "$TMP/snapshot-drift-out" && ok 'snapshot isolates candidate metadata and records drift' || no 'live metadata or records altered replay'
write_cp_hook; cp -a "$b" "$TMP/evidence-drift"; rebase_root "$TMP/evidence-drift"; DRIFT_EVIDENCE="$TMP/evidence-drift/repository/AGENTS.md" DRIFT_EVIDENCE_MARK="$TMP/evidence-mutated" PATH="$TMP/hook-bin:$PATH" "$RUN" gate "$TMP/evidence-drift" "$REC" "$TMP/evidence-drift-out" >/dev/null 2>&1; [ "$?" -ne 0 ] && [ -e "$TMP/evidence-mutated" ] && [ ! -e "$TMP/evidence-drift-out" ] && ok 'repository evidence drift during epoch blocks output' || no 'repository evidence drift was accepted'
cp -a "$b" "$TMP/structural-mutation"; put "$TMP/structural-mutation/record-order/000" malformed; ! reject "$RUN" gate "$TMP/structural-mutation" "$REC" "$TMP/structural-out" && ok 'actual Unit1A rejects old-shallow structural mutation' || no 'structural mutation was accepted'
sed 's/4105381479:9297/0:0/' "$RUN" > "$TMP/payload-tamper"; chmod +x "$TMP/payload-tamper"; ! reject "$TMP/payload-tamper" gate "$b" "$REC" "$TMP/payload-out" && ok 'validator payload digest tamper is rejected' || no 'validator payload tamper was accepted'
cp -a "$REC" "$TMP/obs-input"; tamper_fields "$TMP/obs-input" observation-digest input-digest; ! reject "$RUN" gate "$b" "$TMP/obs-input" "$TMP/obs-input-out" && ok 'observation and input replay drift is rejected' || no 'observation/input replay drift was accepted'
cp -a "$REC" "$TMP/registry"; tamper_fields "$TMP/registry" adapter-id adapter-version adapter-bytes-digest; ! reject "$RUN" gate "$b" "$TMP/registry" "$TMP/registry-out" && ok 'registry version and worker drift is rejected' || no 'registry/version/worker drift was accepted'
cp -a "$REC" "$TMP/identity"; tamper_fields "$TMP/identity" schema kind id attestation-id identity; ! reject "$RUN" gate "$b" "$TMP/identity" "$TMP/identity-out" && ok 'schema record identity and IDs replay exactly' || no 'record identity drift was accepted'
cp -a "$REC" "$TMP/linkage"; tamper_fields "$TMP/linkage" binding-id evidence-fact-id claim-kind; ! reject "$RUN" gate "$b" "$TMP/linkage" "$TMP/linkage-out" && ok 'adapter claim binding and evidence linkage replay exactly' || no 'linkage drift was accepted'
cp -a "$REC" "$TMP/profile"; tamper_fields "$TMP/profile" executable argv-digest method scope source-locator; ! reject "$RUN" gate "$b" "$TMP/profile" "$TMP/profile-out" && ok 'derived executable argv method and scope replay exactly' || no 'derived profile drift was accepted'
cp -a "$b" "$TMP/shared"; cp "$TMP/shared/facts/declaration/observation-refs/000" "$TMP/shared/facts/tool/observation-refs/000"; sync_facts "$TMP/shared"; ! reject "$RUN" gate "$TMP/shared" "$REC" "$TMP/shared-out" && ok 'shared declaration and provider observation blocks' || no 'shared declaration/provider was accepted'
cp -a "$b" "$TMP/swapped"; d="$(get "$TMP/swapped/bindings/unit/declaration-ref")"; p="$(get "$TMP/swapped/bindings/unit/tool-proof-ref")"; put "$TMP/swapped/bindings/unit/declaration-ref" "$p"; put "$TMP/swapped/bindings/unit/tool-proof-ref" "$d"; ! reject "$RUN" gate "$TMP/swapped" "$REC" "$TMP/swapped-out" && ok 'swapped declaration and provider block' || no 'swapped declaration/provider was accepted'
cp -a "$REC" "$TMP/duplicate"; cp -a "$TMP/duplicate/records/000" "$TMP/duplicate/records/002"; ! reject "$RUN" gate "$b" "$TMP/duplicate" "$TMP/duplicate-out" && ok 'duplicate record blocks' || no 'duplicate record was accepted'
cp -a "$REC" "$TMP/extra"; cp -a "$TMP/extra/records/000" "$TMP/extra/records/009"; put "$TMP/extra/records/009/evidence-fact-id" extra; ! reject "$RUN" gate "$b" "$TMP/extra" "$TMP/extra-out" && ok 'extra record blocks' || no 'extra record was accepted'
cp -a "$REC" "$TMP/unsupported"; put "$TMP/unsupported/records/000/adapter-id" made-up-v1; ! reject "$RUN" gate "$b" "$TMP/unsupported" "$TMP/unsupported-out" && ok 'unsupported adapter blocks' || no 'unsupported adapter was accepted'
cp -a "$REC" "$TMP/codegraph-command"; put "$TMP/codegraph-command/records/000/adapter-id" codegraph-v1; put "$TMP/codegraph-command/records/000/claim-kind" command-declaration; ! reject "$RUN" gate "$b" "$TMP/codegraph-command" "$TMP/codegraph-command-out" && ok 'CodeGraph cannot prove command or tool' || no 'CodeGraph command proof was accepted'
cp -a "$REC" "$TMP/codegraph-scope"; put "$TMP/codegraph-scope/records/000/scope" project-root; ! reject "$RUN" gate "$b" "$TMP/codegraph-scope" "$TMP/codegraph-scope-out" && ok 'CodeGraph cannot widen scope' || no 'CodeGraph scope widening was accepted'
cp -a "$REC" "$TMP/unknown"; put "$TMP/unknown/records/000/status" unknown; ! reject "$RUN" gate "$b" "$TMP/unknown" "$TMP/unknown-out" && ok 'unknown non-skip obligation blocks' || no 'unknown obligation was accepted'
g="$TMP/gentle"; bundle_gentle "$g"; "$TMP/records-run" records "$g" "$TMP/gentle-records" || { no 'Gentle detached records'; exit 1; }; ! reject "$RUN" gate "$g" "$TMP/gentle-records" "$TMP/gentle-out" && ok 'unsatisfied Gentle provider blocks repository-only claim' || no 'Gentle unsatisfied provider was accepted'
cp -a "$b" "$TMP/narrow"; put "$TMP/narrow/bindings/unit/signature-coverage" tests; ! reject "$RUN" gate "$TMP/narrow" "$REC" "$TMP/narrow-out" && ok 'narrow conservative scope mismatch blocks' || no 'narrow scope mismatch was accepted'
marker="$TMP/executed"; cp -a "$b" "$TMP/inject"; put "$TMP/inject/bindings/unit/context/executable" "EVIL=1 \$(touch $marker)"; list "$TMP/inject/bindings/unit/context/argv" ';' "\$(touch $marker)"; list "$TMP/inject/bindings/unit/context/env" "EVIL=\$(touch $marker)"; ! reject "$RUN" gate "$TMP/inject" "$REC" "$TMP/inject-out" && [ ! -e "$marker" ] && ok 'candidate executable argv and env remain data' || no 'candidate injection executed or passed'
! reject "$RUN" gate "$b" "$REC" "$TMP/out;touch" && [ ! -e "$TMP/out;touch" ] && [ ! -e "$marker" ] && ok 'output injection is rejected without execution' || no 'output injection was accepted'
if [ ! -e "$TMP/candidate-ran" ]; then ok 'candidate command remains data across replay'; else no 'candidate command executed'; fi
find "$b" -type f -exec cksum {} + | LC_ALL=C sort > "$TMP/candidate-pre"; INTEGRATED="$TMP/integrated"; if "$RUN" integrate "$b" "$REC" "$INTEGRATED" && [ -d "$INTEGRATED" ]; then ok 'integration reconstructs a complete staged bundle'; else no 'integration reconstructs a complete staged bundle'; fi
 [ "$(stat -c %a "$INTEGRATED")" = 700 ] && ok 'integration output retains mode 0700' || no 'integration output mode drifted'
 "$TMP/validator" "$INTEGRATED" >/dev/null && ok 'integration output passes exact Unit1A postcheck' || no 'integration output failed exact Unit1A postcheck'
identity_ok=1; for d in "$INTEGRATED"/attestations/*; do expected="$(attestation_identity "$d")"; actual="$(<"$d/identity")"; want="v1:attestation:$(cksum "$d/identity" | awk '{print $1":"$2}')"; [ "$actual" = "$expected" ] && [ "$(get "$d/id")" = "$want" ] && [ "$(get "$d/attestation-id")" = "$want" ] || { no 'integrated attestations use corrected-1B-a canonical identity bytes'; identity_ok=; break; }; done; [ -n "$identity_ok" ] && ok 'integrated attestations use corrected-1B-a canonical identity bytes'
cp -a "$INTEGRATED" "$TMP/stage-semantic-structural"; put "$TMP/stage-semantic-structural/attestations/000/status" unknown; "$TMP/validator" "$TMP/stage-semantic-structural" >/dev/null && ok 'Unit1A permits semantic-only attestation status mutation' || no 'semantic-only mutation was not structurally isolated'
awk '/semantic=\$stage\/semantic-records/ { print "put \"$stage/attestations/000/status\" unknown" } { print }' "$RUN" > "$TMP/stage-semantic-mutation"; chmod +x "$TMP/stage-semantic-mutation"; ! reject "$TMP/stage-semantic-mutation" integrate "$b" "$REC" "$TMP/stage-semantic-mutation-out" && [ ! -e "$TMP/stage-semantic-mutation-out" ] && ok 'completed-stage semantic replay blocks status mutation before postcheck' || no 'completed-stage semantic mutation was accepted'
find "$b" -type f -exec cksum {} + | LC_ALL=C sort > "$TMP/candidate-post"; cmp -s "$TMP/candidate-pre" "$TMP/candidate-post" && ok 'integration preserves candidate preimage' || no 'integration mutated candidate'
for kind in attestation binding row; do cp -a "$b" "$TMP/stale-$kind"; case "$kind" in attestation) put "$TMP/stale-$kind/attestations/record/id" stale;; binding) put "$TMP/stale-$kind/bindings/unit/id" stale;; row) put "$TMP/stale-$kind/rows/source/id" stale;; esac; ! reject "$RUN" integrate "$TMP/stale-$kind" "$REC" "$TMP/stale-$kind-out" && [ ! -e "$TMP/stale-$kind-out" ] && ok "stale $kind ID is rejected" || no "stale $kind ID was accepted"; done
for kind in row-question reinit; do cp -a "$b" "$TMP/stale-$kind"; case "$kind" in row-question) put "$TMP/stale-$kind/questions/source/row-ref" stale;; reinit) put "$TMP/stale-$kind/reinit/source/row-ref" stale;; esac; ! reject "$RUN" integrate "$TMP/stale-$kind" "$REC" "$TMP/stale-$kind-out" && ok "stale $kind reference is rejected" || no "stale $kind reference was accepted"; done
cp -a "$b" "$TMP/stale-fingerprint"; put "$TMP/stale-fingerprint/facts/tool/source" stale; ! reject "$RUN" integrate "$TMP/stale-fingerprint" "$REC" "$TMP/stale-fingerprint-out" && ok 'stale fingerprint is rejected' || no 'stale fingerprint was accepted'
cp -a "$b" "$TMP/bad-order"; rm -f "$TMP/bad-order/record-order/000"; ! reject "$RUN" integrate "$TMP/bad-order" "$REC" "$TMP/bad-order-out" && ok 'incomplete record-order is rejected' || no 'incomplete record-order was accepted'
 cp -a "$b" "$TMP/reordered"; a="$(get "$TMP/reordered/record-order/000")"; z="$(get "$TMP/reordered/record-order/001")"; put "$TMP/reordered/record-order/000" "$z"; put "$TMP/reordered/record-order/001" "$a"; ! reject "$RUN" integrate "$TMP/reordered" "$REC" "$TMP/reordered-out" && ok 'reordered record-order is rejected' || no 'reordered record-order was accepted'
cp -a "$b" "$TMP/canonical-row-collapse"; cp -a "$TMP/canonical-row-collapse/rows/source" "$TMP/canonical-row-collapse/rows/twin"; put "$TMP/canonical-row-collapse/rows/twin/identity" twin-row; read -r sum bytes _ < <(cksum "$TMP/canonical-row-collapse/rows/twin/identity"); put "$TMP/canonical-row-collapse/rows/twin/id" "v1:row:$sum:$bytes"; twin="$(get "$TMP/canonical-row-collapse/rows/twin/id")"; cp -a "$TMP/canonical-row-collapse/questions/source" "$TMP/canonical-row-collapse/questions/twin"; put "$TMP/canonical-row-collapse/questions/twin/row-ref" "$twin"; put "$TMP/canonical-row-collapse/questions/twin/identity" twin-question; read -r sum bytes _ < <(cksum "$TMP/canonical-row-collapse/questions/twin/identity"); put "$TMP/canonical-row-collapse/questions/twin/id" "v1:question:$sum:$bytes"; refresh_order "$TMP/canonical-row-collapse"; "$TMP/validator" "$TMP/canonical-row-collapse" >/dev/null && ! reject "$RUN" integrate "$TMP/canonical-row-collapse" "$REC" "$TMP/canonical-row-collapse-out" && [ ! -e "$TMP/canonical-row-collapse-out" ] && ok 'real Unit1A rejects naturally collapsed canonical stage rows' || no 'natural canonical row collapse was accepted'
"$RUN" integrate "$b" "$REC" "$TMP/repeat-one" && "$RUN" integrate "$b" "$REC" "$TMP/repeat-two" && diff -r "$TMP/repeat-one" "$TMP/repeat-two" >/dev/null && ok 'integration repeats byte-identically' || no 'integration repeat was nondeterministic'
printf preimage > "$TMP/preimage"; ! reject "$RUN" integrate "$b" "$REC" "$TMP/preimage" && [ "$(get "$TMP/preimage")" = preimage ] && ok 'existing output preimage is preserved' || no 'existing output preimage was changed'
sed 's/"$validator" "$stage" >\/dev\/null || bad/false/' "$RUN" > "$TMP/postcheck-fail"; chmod +x "$TMP/postcheck-fail"; ! reject "$TMP/postcheck-fail" integrate "$b" "$REC" "$TMP/postcheck-out" && [ ! -e "$TMP/postcheck-out" ] && ! compgen -G "$TMP/.postcheck-out.stage.*" >/dev/null && ok 'forced postcheck failure cleans partial stage' || no 'postcheck failure published partial output'
cp -a "$b" "$TMP/integrate-inject"; put "$TMP/integrate-inject/bindings/unit/context/executable" "EVIL=1 \$(touch $marker)"; ! reject "$RUN" integrate "$TMP/integrate-inject" "$REC" "$TMP/integrate-inject-out" && [ ! -e "$marker" ] && ok 'integration keeps candidate executable data-only' || no 'integration executed candidate data'
mkdir "$TMP/.locked.lock"; ! reject "$RUN" integrate "$b" "$REC" "$TMP/locked" && [ ! -e "$TMP/locked" ] && ! compgen -G "$TMP/.locked.stage.*" >/dev/null && ok 'cooperating lock contention fails before stage construction' || no 'lock contention was not fail-closed'; rmdir "$TMP/.locked.lock"
TMPDIR="$TMP" "$RUN" integrate "$b" "$REC" "$TMP/lock-clean" && [ -d "$TMP/lock-clean" ] && [ ! -e "$TMP/.lock-clean.lock" ] && ! compgen -G "$TMP/gentle-ai-rubric-gate.*" >/dev/null && ok 'successful publication releases its lock and workspace' || no 'successful publication leaked lock or workspace'
race="$TMP/race"; TMPDIR="$TMP" "$RUN" integrate "$b" "$REC" "$race" >/dev/null 2>&1 & race_pid=$!; race_ready=; for _ in {1..1000}; do [ -d "$TMP/.race.lock" ] && compgen -G "$TMP/.race.stage.*" >/dev/null && { race_ready=1; break; }; sleep .001; done
if [ -n "$race_ready" ]; then printf preimage > "$race"; wait "$race_pid"; race_status=$?; [ "$race_status" -ne 0 ] && [ "$(get "$race")" = preimage ] && [ ! -e "$TMP/.race.lock" ] && ! compgen -G "$TMP/.race.stage.*" >/dev/null && ! compgen -G "$TMP/.race.receipt.*" >/dev/null && ! compgen -G "$TMP/gentle-ai-rubric-gate.*" >/dev/null && ok 'between-check output race preserves preimage and cleans publication state' || no 'between-check output race was not fail-closed'; else wait "$race_pid"; no 'race synchronization never observed publication lock and stage'; fi
printf '\n%d passed, %d failed\n' "$PASS" "$FAIL"; [ "$FAIL" -eq 0 ]
