#!/usr/bin/env bash
set -uo pipefail
ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
FIX="$ROOT/tests/fixtures/rubric-compiler/adapters"
TMP="$(mktemp -d "${TMPDIR:-/tmp}/gentle-ai-rubric-records.XXXXXX")"; trap 'rm -rf -- "$TMP"' EXIT
PASS=0; FAIL=0
put() { mkdir -p "$(dirname -- "$1")"; printf '%s\n' "$2" > "$1"; }
field() { tr -d '\n' < "$1"; }
sum() { cksum "$1" | awk '{print $1 ":" $2}'; }
ident() { put "$1/kind" "$2"; put "$1/identity" "$3"; put "$1/id" "v1:$2:$(sum "$1/identity")"; }
list() { local d=$1 n=0 x; shift; mkdir -p "$d"; for x; do put "$d/$(printf %03d "$n")" "$x"; n=$((n + 1)); done; }
obs() { local b=$1 n=$2 p=$3; ident "$b/observations/$n" observation "$n"; put "$b/observations/$n/channel" file; put "$b/observations/$n/locator" "$p"; put "$b/observations/$n/checksum" "$(cksum "$b/repo/$p" | awk '{print $1 " " $2}')"; printf '%s\n' "$(field "$b/observations/$n/id")"; }
fact() { local b=$1 n=$2 p=$3 a=$4 k=$5 oid; oid="$(obs "$b" "$n" "$p")"; ident "$b/facts/$n" fact "$n"; put "$b/facts/$n/adapter" "$a"; put "$b/facts/$n/evidence-kind" "$k"; list "$b/facts/$n/observation-refs" "$oid"; printf '%s\n' "$(field "$b/facts/$n/id")"; }
binding() { local b=$1 n=$2 id=$3 exe=$4 scope=$5 d; shift 5; d="$b/bindings/$(printf %03d "$n")"; ident "$d" binding "$id"; put "$d/method" unit; put "$d/scope" "$scope"; put "$d/context/executable" "$exe"; put "$d/context/workdir" .; list "$d/context/argv" "$@"; list "$d/context/env"; }
bundle() {
  local b=$1 sd sp cd cp gd gp; mkdir -p "$b/repo" "$b"/{observations,facts,bindings}; cp -a "$FIX/." "$b/repo/"; put "$b/root" "$b/repo"
  sd="$(fact "$b" shell-decl README.md shell-v1 command-declaration)"; sp="$(fact "$b" shell-proof shell/.github/workflows/test.yml shell-v1 tool-proof)"
  cd="$(fact "$b" cnsic-decl AGENTS.md cnsic-python-v1 command-declaration)"; cp="$(fact "$b" cnsic-proof requirements.txt cnsic-python-v1 tool-proof)"
  gd="$(fact "$b" gentle-decl CONTRIBUTING.md gentle-ai-go-v1 command-declaration)"; gp="$(fact "$b" gentle-proof go.mod gentle-ai-go-v1 tool-proof)"
  binding "$b" 0 shell-unit bash project-root tests/run.sh; list "$b/bindings/000/fact-refs" "$sd" "$sp"
  binding "$b" 1 cnsic-unit python path-prefix:tests/unit -m pytest tests/unit/ -n auto -q; list "$b/bindings/001/fact-refs" "$cd" "$cp"
  binding "$b" 2 gentle-unit go module-root test ./...; list "$b/bindings/002/fact-refs" "$gd" "$gp"
}
extract() { awk -v shape="$1" '$0=="<!-- shape:" shape " -->"{s=1;next}$0=="<!-- /shape:" shape " -->"{exit}s&&/^<!-- rubric-adapter-records:start -->$/{b=1;next}s&&/^<!-- rubric-adapter-records:end -->$/{exit}s&&b{print}' "$ROOT/deltas/sdd-init-rubric.md" > "$2"; [ -s "$2" ] && chmod +x "$2"; }
reject() { "$@" >/dev/null 2>&1 && return 1; return 0; }
pass() { printf 'PASS: %s\n' "$1"; PASS=$((PASS + 1)); }
fail() { printf 'FAIL: %s\n' "$1" >&2; FAIL=$((FAIL + 1)); }
record_for() { local d; for d in "$1/records"/*; do [ "$(field "$d/binding-id")" = "$2" ] && { printf %s "$d"; return; }; done; return 1; }
record_claim() { local d; for d in "$1/records"/*; do [ "$(field "$d/binding-id")" = "$2" ] && [ "$(field "$d/claim-kind")" = "$3" ] && { printf %s "$d"; return; }; done; return 1; }
canonical() { local r=$1 exe=$2 method=$3 scope=$4 argv=$5 status=$6; [ "$(field "$r/executable")" = "$exe" ] && [ "$(field "$r/method")" = "$method" ] && [ "$(field "$r/scope")" = "$scope" ] && [ "$(field "$r/argv-digest")" = "$argv" ] && [ "$(field "$r/status")" = "$status" ]; }
extract details "$TMP/details"; extract pi "$TMP/pi"
cmp -s "$TMP/details" "$TMP/pi" && pass 'Details and Pi records bytes match' || fail 'missing or divergent records directive'
RUN="$TMP/details"; b="$TMP/base"; bundle "$b"; out="$TMP/records"
if "$RUN" records "$b" "$out"; then pass 'exact reviewed profiles emit'; else fail 'exact reviewed profiles emit'; fi
shell_id=$(field "$b/bindings/000/id"); cnsic_id=$(field "$b/bindings/001/id"); gentle_id=$(field "$b/bindings/002/id"); shell=$(record_for "$out" "$shell_id"); shell_proof=$(record_claim "$out" "$shell_id" tool-proof); cnsic=$(record_for "$out" "$cnsic_id"); gentle_decl=$(record_claim "$out" "$gentle_id" command-declaration); gentle_proof=$(record_claim "$out" "$gentle_id" tool-proof)
canonical "$shell" bash unit project-root "$(printf 'tests/run.sh\n' | cksum | awk '{print $1":"$2}')" proven && canonical "$shell_proof" bash unit project-root "$(printf 'tests/run.sh\n' | cksum | awk '{print $1":"$2}')" proven && pass 'closed shell profile and indented workflow proof are canonical' || fail 'shell profile or workflow proof copied caller data or status'
canonical "$cnsic" python unit path-prefix:tests/unit "$(printf '%s\n' -m pytest tests/unit/ -n auto -q | cksum | awk '{print $1":"$2}')" proven && pass 'closed CNSIC profile is canonical' || fail 'CNSIC profile copied caller data or status'
canonical "$gentle_decl" go unit module-root "$(printf '%s\n' test ./... | cksum | awk '{print $1":"$2}')" proven && canonical "$gentle_proof" go unit module-root "$(printf '%s\n' test ./... | cksum | awk '{print $1":"$2}')" unsatisfied && pass 'Gentle declaration proven and provider unsatisfied' || fail 'Gentle claim statuses conflated'
cp -a "$b" "$TMP/gentle-locator"; put "$TMP/gentle-locator/root" "$TMP/gentle-locator/repo"; put "$TMP/gentle-locator/observations/gentle-decl/locator" gentle-ai/CONTRIBUTING.md; put "$TMP/gentle-locator/observations/gentle-decl/checksum" "$(cksum "$TMP/gentle-locator/repo/gentle-ai/CONTRIBUTING.md" | awk '{print $1" "$2}')"; "$RUN" records "$TMP/gentle-locator" "$TMP/gentle-locator-out" && [ "$(field "$(record_claim "$TMP/gentle-locator-out" "$gentle_id" command-declaration)/status")" = unknown ] && pass 'wrong Gentle locator is unknown' || fail 'wrong Gentle locator was unsatisfied or proven'
cp -a "$b" "$TMP/gentle-bytes"; put "$TMP/gentle-bytes/root" "$TMP/gentle-bytes/repo"; printf changed >> "$TMP/gentle-bytes/repo/go.mod"; put "$TMP/gentle-bytes/observations/gentle-proof/checksum" "$(cksum "$TMP/gentle-bytes/repo/go.mod" | awk '{print $1" "$2}')"; "$RUN" records "$TMP/gentle-bytes" "$TMP/gentle-bytes-out" && [ "$(field "$(record_claim "$TMP/gentle-bytes-out" "$gentle_id" tool-proof)/status")" = unknown ] && pass 'wrong Gentle bytes are unknown' || fail 'wrong Gentle bytes were unsatisfied or proven'
if find "$b" -type f -exec cksum {} + > "$TMP/pre" && "$RUN" records "$b" "$TMP/second" && find "$b" -type f -exec cksum {} + > "$TMP/post" && cmp -s "$TMP/pre" "$TMP/post" && diff -r "$out" "$TMP/second" >/dev/null && [ "$(stat -c %a "$out")" = 700 ]; then pass 'detached deterministic mode-0700 output preserves preimage'; else fail 'detached deterministic output'; fi
for f in executable method scope; do cp -a "$b" "$TMP/spoof-$f"; put "$TMP/spoof-$f/bindings/000/${f/context\/executable}" spoofed; done
put "$TMP/spoof-executable/bindings/000/context/executable" sh; put "$TMP/spoof-method/bindings/000/method" lint; put "$TMP/spoof-scope/bindings/000/scope" widened
for f in executable method scope; do "$RUN" records "$TMP/spoof-$f" "$TMP/spoof-$f-out" && r=$(record_for "$TMP/spoof-$f-out" "$shell_id") && canonical "$r" bash unit project-root "$(printf 'tests/run.sh\n' | cksum | awk '{print $1":"$2}')" unknown && pass "caller $f spoof is derived unknown" || fail "caller $f spoof was accepted"; done
n=0; for p in docs/README.md tests/run.sh; do look="$TMP/look-$n"; cp -a "$b" "$look"; put "$look/root" "$look/repo"; mkdir -p "$(dirname "$look/repo/$p")"; cp "$b/repo/README.md" "$look/repo/$p"; put "$look/observations/shell-decl/locator" "$p"; put "$look/observations/shell-decl/checksum" "$(cksum "$look/repo/$p" | awk '{print $1" "$2}')"; "$RUN" records "$look" "$look-out" && [ "$(field "$(record_for "$look-out" "$shell_id")/status")" = unknown ] && pass "lookalike $p is unknown" || fail "lookalike $p was proven"; n=$((n + 1)); done
cp -a "$b" "$TMP/version"; put "$TMP/version/facts/shell-decl/adapter-version" v2; "$RUN" records "$TMP/version" "$TMP/version-out" && [ "$(field "$(record_for "$TMP/version-out" "$shell_id")/status")" = unknown ] && pass 'registry version substitution is unknown' || fail 'registry version substitution was accepted'
cp -a "$b" "$TMP/unsupported"; put "$TMP/unsupported/facts/shell-decl/adapter" made-up-v1; "$RUN" records "$TMP/unsupported" "$TMP/unsupported-out" && r=$(record_claim "$TMP/unsupported-out" "$shell_id" command-declaration) && [ "$(field "$r/status")" = unknown ] && [ "$(field "$r/adapter-version")" = unknown ] && [ "$(field "$r/adapter-bytes-digest")" = none ] && pass 'unsupported adapter is canonical unknown without worker execution' || fail 'unsupported adapter was accepted'
cp -a "$b" "$TMP/replay"; put "$TMP/replay/root" "$TMP/replay/repo"; printf changed >> "$TMP/replay/repo/README.md"; reject "$RUN" records "$TMP/replay" "$TMP/replay-out" && [ ! -e "$TMP/replay-out" ] && pass 'observation/input digest replay fails atomically' || fail 'digest replay published output'
awk '{gsub(/[0-9]+:[0-9]+/, "0:0"); print}' "$RUN" > "$TMP/tampered"; chmod +x "$TMP/tampered"; reject "$TMP/tampered" records "$b" "$TMP/tampered-out" && [ ! -e "$TMP/tampered-out" ] && pass 'pinned worker substitution fails atomically' || fail 'worker substitution published output'
marker="$TMP/executed"; cp -a "$b" "$TMP/inject"; put "$TMP/inject/bindings/000/context/executable" "EVIL=1 \$(touch $marker) > $marker"; list "$TMP/inject/bindings/000/context/argv" ';' "\$(touch $marker)"; list "$TMP/inject/bindings/000/context/env" "EVIL=\$(touch $marker)"; "$RUN" records "$TMP/inject" "$TMP/inject-out" && [ ! -e "$marker" ] && [ "$(field "$(record_for "$TMP/inject-out" "$shell_id")/status")" = unknown ] && pass 'operators argv env and redirection remain data' || fail 'candidate injection executed or proved'
reject "$RUN" records "$b" "$TMP/out;touch" && [ ! -e "$TMP/out;touch" ] && pass 'output injection is rejected' || fail 'output injection was accepted'
cp -a "$b" "$TMP/traversal"; put "$TMP/traversal/observations/shell-decl/locator" ../README.md; reject "$RUN" records "$TMP/traversal" "$TMP/traversal-out" && [ ! -e "$TMP/traversal-out" ] && pass 'confinement failure cleans staging' || fail 'confinement failure published output'
cp -a "$b" "$TMP/symlink"; put "$TMP/symlink/root" "$TMP/symlink/repo"; mkdir "$TMP/symlink/repo/real"; cp "$TMP/symlink/repo/README.md" "$TMP/symlink/repo/real/README.md"; ln -s real "$TMP/symlink/repo/link"; put "$TMP/symlink/observations/shell-decl/locator" link/README.md; reject "$RUN" records "$TMP/symlink" "$TMP/symlink-out" && [ ! -e "$TMP/symlink-out" ] && pass 'intermediate symlink rejects and cleans staging' || fail 'intermediate symlink published output'
mkdir -p "$TMP/graph"/{observations,facts,bindings}; put "$TMP/graph/root" "$b/repo"; ident "$TMP/graph/observations/000" observation graph; for x in channel:codegraph status:untrusted scope:scope-only query:symbols index-revision:v1 symbol:README repo-path:README.md source:fixture provenance:observed; do put "$TMP/graph/observations/000/${x%%:*}" "${x#*:}"; done; ident "$TMP/graph/facts/000" fact graph; put "$TMP/graph/facts/000/adapter" codegraph-v1; put "$TMP/graph/facts/000/evidence-kind" scope-only; list "$TMP/graph/facts/000/observation-refs" "$(field "$TMP/graph/observations/000/id")"; binding "$TMP/graph" 0 graph-unit runner scope-only; list "$TMP/graph/bindings/000/fact-refs" "$(field "$TMP/graph/facts/000/id")"
graph_id=$(field "$TMP/graph/bindings/000/id"); "$RUN" records "$TMP/graph" "$TMP/graph-out" && r=$(record_for "$TMP/graph-out" "$graph_id") && canonical "$r" unknown unknown scope-only none unknown && pass 'CodeGraph is deferred unknown scope-only' || fail 'CodeGraph widened scope or proved command/tool'
cp -a "$TMP/graph" "$TMP/graph-command"; put "$TMP/graph-command/facts/000/evidence-kind" command-declaration; "$RUN" records "$TMP/graph-command" "$TMP/graph-command-out" && [ "$(field "$(record_for "$TMP/graph-command-out" "$graph_id")/status")" = unknown ] && pass 'CodeGraph command/tool proof is denied' || fail 'CodeGraph command claim was proven'
printf '\n%d passed, %d failed\n' "$PASS" "$FAIL"; [ "$FAIL" -eq 0 ]
