#!/usr/bin/env bash
set -uo pipefail
ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"; TMP="$(mktemp -d "${TMPDIR:-/tmp}/gentle-ai-rubric-activation.XXXXXX")"; trap 'rm -rf -- "$TMP"' EXIT; PASS=0; FAIL=0
ok() { printf 'PASS: %s\n' "$1"; PASS=$((PASS + 1)); }; no() { printf 'FAIL: %s\n' "$1" >&2; FAIL=$((FAIL + 1)); }; reject() { "$@" >/dev/null 2>&1; }
extract_block() { awk -v s="$1" -v n="$2" '$0=="<!-- shape:"s" -->"{a=1;next}$0=="<!-- /shape:"s" -->"{exit}a&&$0=="<!-- rubric-"n":start -->"{b=1;next}a&&$0=="<!-- rubric-"n":end -->"{exit}b{print}' "$ROOT/deltas/sdd-init-rubric.md" > "$3"; chmod +x "$3"; }
field() { awk -F= -v k="$2" '$1==k{n++;v=substr($0,length(k)+2)}END{if(n==1)print v;else exit 1}' "$1"; }
model() { field "$1" canonical_model_bytes | sed 's/^hex://' | xxd -r -p; }
receipt() { for k in schema state gate_version gate_digest integrated_bundle_digest semantic_digest canonical_model_bytes canonical_model_digest commits; do field "$1" "$k" >/dev/null || return 1; done; grep -Fxq 'schema=IntegratedValidationV1' "$1" && grep -Fxq 'state=verified' "$1" && grep -Fxq 'gate_version=v1' "$1" && grep -Fxq 'commits=none' "$1"; }
definitions() { awk -v n="$2" '$0 ~ ("^" n "\\(\\)") { c++ } END { print c+0 }' "$1"; }
outside() { local in=$1 part=$2 start end; start=$(awk '/^testing:[[:space:]]*$/{n++;x=NR}END{if(n==1)print x;else exit 1}' "$in") || return 1; end=$(awk -v n="$start" 'NR>n&&/^[A-Za-z_][A-Za-z0-9_-]*:/{print NR;exit}' "$in") || return 1; case "$part" in prefix) awk -v n="$start" 'NR<n{print}';; suffix) awk -v n="$end" 'NR>=n{print}';; esac < "$in"; }
# shellcheck disable=SC1091
source "$ROOT/tests/lib/rubric-compiler-cnsic-fixture.sh"; rccf_load_unit1a "$ROOT" "$TMP"
# shellcheck disable=SC1091
source "$ROOT/tests/lib/rubric-engram-store.sh"
extract_block details adapter-gate "$TMP/gate"; extract_block pi adapter-gate "$TMP/pi"; extract_block details adapter-records "$TMP/records"; extract_block details validator "$TMP/validator"; extract_block details activation "$TMP/activation"; extract_block pi activation "$TMP/pi-activation"
cmp -s "$TMP/gate" "$TMP/pi" && [ -s "$TMP/gate" ] && ok 'Details and Pi integrated gate bytes match' || no 'missing or divergent integrated gate'
cmp -s "$TMP/activation" "$TMP/pi-activation" && [ -s "$TMP/activation" ] && ok 'Details and Pi activation transaction bytes match' || no 'missing or divergent activation transaction'
for n in model ms mval mf mr ml mvs mid mrefs mobs mfact matt mbind mrow; do [ "$(definitions "$TMP/gate" "$n")" = 1 ] && [ "$(definitions "$TMP/pi" "$n")" = 1 ] || { no "duplicate or missing canonical serializer $n"; break; }; done; [ "$FAIL" -eq 0 ] && ok 'each gate defines one canonical serializer' || :
b="$TMP/candidate"; rccf_cnsic_candidate "$b"; "$TMP/validator" "$b" >/dev/null && ok 'shared CNSIC fixture is exact Unit1A-valid' || no 'shared CNSIC fixture is not Unit1A-valid'
"$TMP/records" records "$b" "$TMP/records-set" && "$TMP/gate" integrate "$b" "$TMP/records-set" "$TMP/integrated" && rccf_confirm "$TMP/integrated" && "$TMP/validator" "$TMP/integrated" >/dev/null && ok 'real candidate records integrate and canonical confirmation rebuilds Unit1A identities' || no 'real pipeline or canonical confirmation failed'
"$TMP/gate" verify-integrated "$TMP/integrated" "$TMP/pre-activation" || no 'pre-activation integrated receipt failed'
cp "$ROOT/openspec/config.yaml" "$TMP/actual.yaml"; outside "$TMP/actual.yaml" prefix > "$TMP/actual.prefix"; outside "$TMP/actual.yaml" suffix > "$TMP/actual.suffix"; "$TMP/activation" activate-openspec cnsic "$TMP/integrated" "$TMP/actual.yaml" "$TMP/actual-resolution" "$TMP/gate" && cmp -s "$TMP/actual.prefix" <(outside "$TMP/actual.yaml" prefix) && cmp -s "$TMP/actual.suffix" <(outside "$TMP/actual.yaml" suffix) && grep -Fxq '  policy: "rubric"' "$TMP/actual.yaml" && grep -Fxq '  rubric:' "$TMP/actual.yaml" && grep -Fxq '    schema: "ResolutionV1"' "$TMP/actual.yaml" && grep -Fxq '    state: "active"' "$TMP/actual.yaml" && grep -Fq '    txn_id: "v1:' "$TMP/actual.yaml" && grep -Fxq '    authority: "openspec"' "$TMP/actual.yaml" && grep -Fq '    canonical_model_digest: "' "$TMP/actual.yaml" && grep -Fxq 'authority=openspec' "$TMP/actual-resolution" && grep -Fxq 'readback=verified' "$TMP/actual-resolution" && grep -Fxq '    resolution:' "$TMP/actual.yaml" && grep -Fxq '    bindings:' "$TMP/actual.yaml" && grep -Fxq '    rows:' "$TMP/actual.yaml" && ! grep -Fxq '  policy:' "$TMP/actual.yaml" && ok 'actual OpenSpec config preserves byte-exact exterior and canonical rubric shape' || no 'actual OpenSpec config compatibility or canonical shape failed'
cp "$TMP/actual.yaml" "$TMP/actual-once"; "$TMP/activation" activate-openspec cnsic "$TMP/integrated" "$TMP/actual.yaml" "$TMP/actual-resolution-two" "$TMP/gate" && cmp -s "$TMP/actual-once" "$TMP/actual.yaml" && cmp -s "$TMP/actual.prefix" <(outside "$TMP/actual.yaml" prefix) && cmp -s "$TMP/actual.suffix" <(outside "$TMP/actual.yaml" suffix) && ok 'actual config repeat preserves exact prefix and suffix' || no 'actual config repeat changed exterior bytes'
cat > "$TMP/config.yaml" <<'EOF'
context: "preserve"
testing:
  legacy: "replace"
strict_tdd: false
rules:
  apply: "preserve"
EOF
cp "$TMP/config.yaml" "$TMP/config-before"; "$TMP/activation" activate-openspec cnsic "$TMP/integrated" "$TMP/config.yaml" "$TMP/resolution" "$TMP/gate" && grep -Fq '# gentle-ai:managed-testing:start' "$TMP/config.yaml" && grep -Fq 'command:' "$TMP/config.yaml" && grep -Fq 'rows:' "$TMP/config.yaml" && grep -Fq 'context: "preserve"' "$TMP/config.yaml" && grep -Fq 'rules:' "$TMP/config.yaml" && [ "$(field "$TMP/resolution" canonical_model_digest)" = "$(field "$TMP/pre-activation" canonical_model_digest)" ] && ok 'pinned gate serializes complete YAML and preserves unrelated bytes' || no 'OpenSpec serializer or transaction failed'
cp "$TMP/config.yaml" "$TMP/config-once"; "$TMP/activation" activate-openspec cnsic "$TMP/integrated" "$TMP/config.yaml" "$TMP/resolution-two" "$TMP/gate" && cmp -s "$TMP/config-once" "$TMP/config.yaml" && ok 'activation is byte-idempotent' || no 'activation was not idempotent'
cp "$TMP/config-before" "$TMP/pi-config.yaml"; "$TMP/pi-activation" activate-openspec cnsic "$TMP/integrated" "$TMP/pi-config.yaml" "$TMP/pi-resolution" "$TMP/pi" && cmp -s "$TMP/config.yaml" "$TMP/pi-config.yaml" && ok 'Pi activation executes the exact Details transaction' || no 'Pi activation differs from Details transaction'
for kind in zero multiple tabs directive anchor alias tag merge block partial; do cp "$TMP/config-before" "$TMP/$kind.yaml"; case "$kind" in zero) printf '%s\n' 'context: "x"' 'strict_tdd: false' 'rules: {}' > "$TMP/$kind.yaml";; multiple) printf '%s\n' 'testing:' '  x: y' 'testing:' '  z: q' 'strict_tdd: false' 'rules: {}' > "$TMP/$kind.yaml";; tabs) printf '\ttesting:\n' >> "$TMP/$kind.yaml";; directive) printf '%s\n' '---' >> "$TMP/$kind.yaml";; anchor) printf '%s\n' 'x: &shared value' >> "$TMP/$kind.yaml";; alias) printf '%s\n' 'x: *shared' >> "$TMP/$kind.yaml";; tag) printf '%s\n' 'x: !unsafe value' >> "$TMP/$kind.yaml";; merge) printf '%s\n' '<<: *shared' >> "$TMP/$kind.yaml";; block) printf '%s\n' 'context: "x"' 'testing:' '  legacy: |' '    block' 'strict_tdd: false' 'rules: {}' > "$TMP/$kind.yaml";; partial) printf '%s\n' '  # gentle-ai:managed-testing:start' >> "$TMP/$kind.yaml";; esac; cp "$TMP/$kind.yaml" "$TMP/$kind.before"; ! reject "$TMP/activation" activate-openspec cnsic "$TMP/integrated" "$TMP/$kind.yaml" "$TMP/$kind.result" "$TMP/gate" && cmp -s "$TMP/$kind.before" "$TMP/$kind.yaml" && [ ! -e "$TMP/$kind.result" ] && ok "$kind target rejects unchanged" || no "$kind target changed or accepted"; done
cp "$TMP/gate" "$TMP/substituted-gate"; printf x >> "$TMP/substituted-gate"; ! reject "$TMP/activation" activate-openspec cnsic "$TMP/integrated" "$TMP/config-before" "$TMP/substituted-result" "$TMP/substituted-gate" && [ ! -e "$TMP/substituted-result" ] && ok 'substituted or extra caller policy input rejects' || no 'unpinned gate accepted'; ! reject "$TMP/activation" activate-openspec cnsic "$TMP/integrated" "$TMP/config-before" "$TMP/extra-result" "$TMP/gate" extra && ok 'caller policy argument is impossible' || no 'caller policy argument was accepted'
before=$(cksum "$TMP/config-before"); out=$("$TMP/activation" evaluate-none cnsic "$TMP/integrated" "$TMP/gate") && [ "$(cksum "$TMP/config-before")" = "$before" ] && [ ! -e "$TMP/none-result" ] && printf '%s' "$out" | grep -Fq 'canonical_model_digest=' && ok 'none prints model envelope with zero target or receipt writes' || no 'none mode wrote or omitted model'
rces_init "$TMP/engram-store"
"$TMP/activation" activate-engram cnsic "$TMP/integrated" "$ROOT/tests/lib/rubric-engram-store.sh" "$TMP/engram-store" "$TMP/gate" > "$TMP/engram-resolution" && ok 'Engram-only first activation reaches verified active' || no 'Engram-only first activation did not reach active'
grep -Fxq 'state=active' "$TMP/engram-resolution" && grep -Fxq 'engram_preimage_presence=absent' "$TMP/engram-resolution" && grep -Fxq 'state=active' <(rces_field "$TMP/engram-store/current" content_hex | xxd -r -p) && ok 'active resolution follows both verified read-backs with readable model metadata' || no 'resolution or canonical Markdown metadata was incomplete'
printf 'prior canonical bytes\n' > "$TMP/prior"; rces_init "$TMP/update-store"; rces_seed "$TMP/update-store" sdd-init/cnsic "$TMP/prior"; prior_hex=$(rces_hex "$TMP/prior"); prior_digest=$(rces_digest "$TMP/prior"); "$TMP/activation" activate-engram cnsic "$TMP/integrated" "$ROOT/tests/lib/rubric-engram-store.sh" "$TMP/update-store" "$TMP/gate" > "$TMP/update-resolution" && grep -Fxq 'engram_preimage_presence=found' "$TMP/update-resolution" && grep -Fxq 'engram_preimage_revision=1' "$TMP/update-resolution" && grep -Fxq "engram_preimage_digest=$prior_digest" "$TMP/update-resolution" && grep -Fxq "engram_preimage_hex=$prior_hex" "$TMP/update-resolution" && ok 'existing active update retains exact preimage metadata' || no 'existing preimage metadata was lost'
for fault in malformed duplicate ambiguous version-only error stale lie-put post-missing post-mismatch; do rces_init "$TMP/$fault-store"; rces_mode "$TMP/$fault-store" "$fault"; ! reject "$TMP/activation" activate-engram cnsic "$TMP/integrated" "$ROOT/tests/lib/rubric-engram-store.sh" "$TMP/$fault-store" "$TMP/gate" && { [ ! -f "$TMP/$fault-store/current" ] || ! grep -Fxq 'state=active' <(rces_field "$TMP/$fault-store/current" content_hex | xxd -r -p); } && ok "$fault adapter failure cannot report active" || no "$fault adapter failure was accepted"; done
rces_request "$TMP/bad-request" schema EngramAdapterV1 verb unknown request_id one project cnsic topic sdd-init/cnsic; ! reject "$ROOT/tests/lib/rubric-engram-store.sh" "$TMP/engram-store" "$TMP/bad-request" "$TMP/bad-response" && rces_request "$TMP/bad-request" schema EngramAdapterV1 verb lookup-canonical request_id one project cnsic && ! reject "$ROOT/tests/lib/rubric-engram-store.sh" "$TMP/engram-store" "$TMP/bad-request" "$TMP/bad-response" && ok 'adapter rejects unknown and malformed fixed-verb requests' || no 'adapter accepted unknown or malformed request'
marker="$TMP/engram-payload-executed"; ! reject "$TMP/activation" activate-engram "bad;\$(touch $marker)" "$TMP/integrated" "$ROOT/tests/lib/rubric-engram-store.sh" "$TMP/engram-store" "$TMP/gate" && [ ! -e "$marker" ] && ok 'payload-like project and paths remain data under fixed argv' || no 'payload-like Engram input executed'
for payload in requirements.txt CMakeLists.txt README.sh README.mdx; do mkdir "$TMP/$payload"; rces_init "$TMP/$payload"; ! reject "$TMP/activation" activate-engram "bad;\$(touch $TMP/$payload-ran)" "$TMP/integrated" "$ROOT/tests/lib/rubric-engram-store.sh" "$TMP/$payload" "$TMP/gate" && [ ! -e "$TMP/$payload-ran" ] && ok "$payload remains non-executable data" || no "$payload was interpreted"; done
cp "$TMP/config-before" "$TMP/hybrid.yaml"; rces_init "$TMP/hybrid-store"; "$TMP/activation" activate-hybrid cnsic "$TMP/integrated" "$TMP/hybrid.yaml" "$TMP/hybrid.journal" "$ROOT/tests/lib/rubric-engram-store.sh" "$TMP/hybrid-store" "$TMP/gate" > "$TMP/hybrid-resolution" && grep -Fxq 'state=active' "$TMP/hybrid-resolution" && grep -Fxq 'current_intent=active' "$TMP/hybrid.journal" && grep -Fxq '    state: "active"' "$TMP/hybrid.yaml" && grep -Fxq 'state=active' <(rces_field "$TMP/hybrid-store/current" content_hex | xxd -r -p) && ok 'hybrid commits verified OpenSpec and Engram active surfaces in order' || no 'hybrid did not reach verified active surfaces'
cp "$TMP/hybrid.journal" "$TMP/hybrid.journal.once"; cp "$TMP/hybrid.yaml" "$TMP/hybrid.yaml.once"; cp "$TMP/hybrid-store/current" "$TMP/hybrid-store/current.once"; "$TMP/activation" activate-hybrid cnsic "$TMP/integrated" "$TMP/hybrid.yaml" "$TMP/hybrid.journal" "$ROOT/tests/lib/rubric-engram-store.sh" "$TMP/hybrid-store" "$TMP/gate" > "$TMP/hybrid-replay" && cmp -s "$TMP/hybrid.journal.once" "$TMP/hybrid.journal" && cmp -s "$TMP/hybrid.yaml.once" "$TMP/hybrid.yaml" && cmp -s "$TMP/hybrid-store/current.once" "$TMP/hybrid-store/current" && cmp -s "$TMP/hybrid-resolution" "$TMP/hybrid-replay" && ok 'same transaction active replay is byte-idempotent' || no 'same transaction active replay rewrote active state'
cp -a "$TMP/integrated" "$TMP/hybrid-different"; put "$TMP/hybrid-different/rows/source/mode" strict-tdd; rccf_rebuild_confirmation "$TMP/hybrid-different"; ! reject "$TMP/activation" activate-hybrid cnsic "$TMP/hybrid-different" "$TMP/hybrid.yaml" "$TMP/hybrid.journal" "$ROOT/tests/lib/rubric-engram-store.sh" "$TMP/hybrid-store" "$TMP/gate" && cmp -s "$TMP/hybrid.journal.once" "$TMP/hybrid.journal" && ok 'different transaction cannot reuse active journal' || no 'different transaction reused journal'
# The production program exposes only stable comments.  Each runner copy crashes
# through sed; activation has no environment-variable or test-only bypass.
crash_points=(F1-before-intent F1-after-intent F1-before-write F1-after-write F1-before-readback F1-after-readback F2-before-intent F2-after-intent F2-before-write F2-after-write F2-before-readback F2-after-readback F3-before-intent F3-after-intent F3-before-write F3-after-write F3-before-readback F3-after-readback F4-before-intent F4-after-intent F4-before-write F4-after-write F4-before-readback F4-after-readback)
crash_ok=1
for point in "${crash_points[@]}"; do
  runner="$TMP/crash-$point"; sed "/# crash:$point$/a exit 75" "$TMP/activation" > "$runner"; chmod +x "$runner"
  cp "$TMP/config-before" "$TMP/$point.yaml"; rces_init "$TMP/$point-store"
  ! reject "$runner" activate-hybrid cnsic "$TMP/integrated" "$TMP/$point.yaml" "$TMP/$point.journal" "$ROOT/tests/lib/rubric-engram-store.sh" "$TMP/$point-store" "$TMP/gate" || crash_ok=0
  case "$point" in *-after-*|F[2-4]-before-*) [ -f "$TMP/$point.journal" ] || crash_ok=0;; esac
  "$TMP/activation" activate-hybrid cnsic "$TMP/integrated" "$TMP/$point.yaml" "$TMP/$point.journal" "$ROOT/tests/lib/rubric-engram-store.sh" "$TMP/$point-store" "$TMP/gate" > "$TMP/$point.out" || crash_ok=0
  grep -Fxq 'state=active' "$TMP/$point.out" && grep -Fxq 'current_intent=active' "$TMP/$point.journal" || crash_ok=0
done
[ "$crash_ok" = 1 ] && ok 'F1-F4 write-ahead crash matrix resumes only from independently verified intents' || no 'write-ahead crash matrix did not resume safely'
compcase() {
  local runner=$1 name=$2 want=$3 yaml journal store; yaml="$TMP/$name.yaml"; journal="$TMP/$name.journal"; store="$TMP/$name-store"
  cp "$TMP/config-before" "$yaml"; cp "$yaml" "$yaml.raw"; printf 'raw %s\n' "$name" > "$TMP/$name.raw"; rces_init "$store"; rces_seed "$store" sdd-init/cnsic "$TMP/$name.raw"
  "$runner" activate-hybrid cnsic "$TMP/integrated" "$yaml" "$journal" "$ROOT/tests/lib/rubric-engram-store.sh" "$store" "$TMP/gate" >/dev/null || :
  "$TMP/activation" activate-hybrid cnsic "$TMP/integrated" "$yaml" "$journal" "$ROOT/tests/lib/rubric-engram-store.sh" "$store" "$TMP/gate" >/dev/null || return 1
  actual_rev=$(rces_field "$store/current" store_revision); [ "$actual_rev" = "$(field "$journal" engram_restore_revision)" ] || return 1; case "$name" in *F2-*|*F3-*|*F4-*) [ "$actual_rev" != "$(field "$journal" engram_preimage_revision)" ] || return 1;; esac
  case "$want" in prior-active) cmp -s "$yaml.raw" "$yaml" && cmp -s "$TMP/$name.raw" <(rces_field "$store/current" content_hex | xxd -r -p) && grep -Fxq 'state=prior-active' "$journal" && grep -Fxq 'current_intent=prior-active' "$journal" && grep -Fxq 'verified_step=C1-verified' "$journal";; active) grep -Fxq 'state=active' "$journal" && grep -Fxq 'current_intent=active' "$journal";; esac || return 1
  cp "$journal" "$journal.once"; cp "$yaml" "$yaml.once"; cp "$store/current" "$store/current.once"
  "$TMP/activation" activate-hybrid cnsic "$TMP/integrated" "$yaml" "$journal" "$ROOT/tests/lib/rubric-engram-store.sh" "$store" "$TMP/gate" >/dev/null && cmp -s "$journal.once" "$journal" && cmp -s "$yaml.once" "$yaml" && cmp -s "$store/current.once" "$store/current"
}
comp_ok=1
for spec in 'F1-completed:prior-active' 'F2-completed:prior-active' 'F3-completed:prior-active' 'F4-before-terminal:prior-active'; do
  point=${spec%%:*}; want=${spec#*:}; runner="$TMP/forward-failure-$point"; sed "/# fault:$point\$/a return 77" "$TMP/activation" > "$runner"; chmod +x "$runner"; compcase "$runner" "forward-failure-$point" "$want" || comp_ok=0
done
[ "$comp_ok" = 1 ] && ok 'F1-F4 deterministic failures restore exact raw preimages or retain verified active terminals' || no 'forward failure compensation or terminal replay failed'
c_ok=1
for point in C1-before-intent C1-after-intent C1-before-write C1-after-write C1-before-readback C1-after-readback C2-before-intent C2-after-intent C2-before-write C2-after-write C2-before-readback C2-after-readback C3-before-intent C3-after-intent C3-before-write C3-after-write C3-before-readback C3-after-readback C4-before-intent C4-after-intent C4-before-write C4-after-write C4-before-readback C4-after-readback; do
  phase=F4-before-terminal; case "$point" in C1-*) phase=F1-before-F2;; C2-*) phase=F2-completed;; C3-*) phase=F3-completed;; esac; runner="$TMP/comp-crash-$point"; sed "/# fault:$phase\$/a return 77" "$TMP/activation" | sed "/# crash:$point\$/a exit 75" > "$runner"; chmod +x "$runner"; cp "$TMP/config-before" "$TMP/$point.yaml"; cp "$TMP/$point.yaml" "$TMP/$point.raw"; printf 'raw %s\n' "$point" > "$TMP/$point.raw.engram"; rces_init "$TMP/$point-store"; rces_seed "$TMP/$point-store" sdd-init/cnsic "$TMP/$point.raw.engram"
  "$runner" activate-hybrid cnsic "$TMP/integrated" "$TMP/$point.yaml" "$TMP/$point.journal" "$ROOT/tests/lib/rubric-engram-store.sh" "$TMP/$point-store" "$TMP/gate" >/dev/null 2>&1; [ "$?" = 75 ] || { printf 'marker missed: %s\n' "$point" >&2; c_ok=0; }
  "$TMP/activation" activate-hybrid cnsic "$TMP/integrated" "$TMP/$point.yaml" "$TMP/$point.journal" "$ROOT/tests/lib/rubric-engram-store.sh" "$TMP/$point-store" "$TMP/gate" >/dev/null && cmp -s "$TMP/$point.raw" "$TMP/$point.yaml" && cmp -s "$TMP/$point.raw.engram" <(rces_field "$TMP/$point-store/current" content_hex | xxd -r -p) && grep -Fxq 'state=prior-active' "$TMP/$point.journal" && grep -Fxq 'current_intent=prior-active' "$TMP/$point.journal" || { printf 'resume failed: %s\n' "$point" >&2; c_ok=0; }
done
[ "$c_ok" = 1 ] && ok 'C1-C4 write-ahead compensation crash matrix restores exact raw surfaces' || no 'compensation crash matrix did not resume safely'
cp "$TMP/hybrid.journal" "$TMP/stale.journal"; sed -i 's/^generation=.*/generation=0/' "$TMP/stale.journal"; cp "$TMP/stale.journal" "$TMP/stale.once"; ! reject "$TMP/activation" activate-hybrid cnsic "$TMP/integrated" "$TMP/hybrid.yaml" "$TMP/stale.journal" "$ROOT/tests/lib/rubric-engram-store.sh" "$TMP/hybrid-store" "$TMP/gate" && cmp -s "$TMP/stale.once" "$TMP/stale.journal" && ok 'stale journal generation rejects without overwrite' || no 'stale journal generation overwrote state'
cp "$TMP/config-before" "$TMP/conflict.yaml"; rces_init "$TMP/conflict-store"; "$TMP/activation" activate-hybrid cnsic "$TMP/integrated" "$TMP/conflict.yaml" "$TMP/conflict.journal" "$ROOT/tests/lib/rubric-engram-store.sh" "$TMP/conflict-store" "$TMP/gate" >/dev/null; printf 'conflict\n' >> "$TMP/conflict.yaml"; ! reject "$TMP/activation" activate-hybrid cnsic "$TMP/integrated" "$TMP/conflict.yaml" "$TMP/conflict.journal" "$ROOT/tests/lib/rubric-engram-store.sh" "$TMP/conflict-store" "$TMP/gate" && grep -Fxq 'state=recovery-required' "$TMP/conflict.journal" && ok 'unexpected independently read surface becomes recovery-required' || no 'unexpected surface was not retained for recovery'
[ ! -e "$TMP/integrated/activation/unit1a-result" ] && [ ! -e "$TMP/integrated/activation/semantic-result" ] && ok 'real integrated fixture has no activation markers' || no 'fixture retained activation markers'
if "$TMP/gate" verify-integrated "$TMP/integrated" "$TMP/one" && "$TMP/gate" verify-integrated "$TMP/integrated" "$TMP/two" && cmp -s "$TMP/one" "$TMP/two" && receipt "$TMP/one" && model "$TMP/one" | grep -Fq 'CanonicalPolicyModelV1' && model "$TMP/one" | grep -Fq 'python' && model "$TMP/one" | grep -Fq 'pytest'; then ok 'verified integrated receipt is byte-identical, complete, and content-bound'; else no 'verified integrated receipt'; fi
for kind in marker shallow unconfirmed open unknown unsatisfied identity; do cp -a "$TMP/integrated" "$TMP/$kind"; case "$kind" in marker) mkdir -p "$TMP/$kind/activation"; put "$TMP/$kind/activation/unit1a-result" structure-valid/pending;; shallow) rm -rf "${TMP:?}/$kind"; mkdir "$TMP/$kind"; put "$TMP/$kind/activation/unit1a-result" structure-valid/pending;; unconfirmed) put "$TMP/$kind/rows/source/state" pending;; open) put "$TMP/$kind/questions/source/state" open;; unknown) put "$TMP/$kind/facts/declaration/status" unknown;; unsatisfied) put "$TMP/$kind/attestations/000/status" unsatisfied;; identity) put "$TMP/$kind/rows/source/id" stale;; esac; ! reject "$TMP/gate" verify-integrated "$TMP/$kind" "$TMP/$kind-receipt" && [ ! -e "$TMP/$kind-receipt" ] && ok "$kind input rejects without receipt" || no "$kind input was accepted"; done
cp -a "$TMP/integrated" "$TMP/policy"; put "$TMP/policy/rows/source/mode" strict-tdd; rccf_rebuild_confirmation "$TMP/policy"; "$TMP/validator" "$TMP/policy" >/dev/null && "$TMP/gate" verify-integrated "$TMP/policy" "$TMP/policy-receipt" && [ "$(field "$TMP/one" integrated_bundle_digest)" != "$(field "$TMP/policy-receipt" integrated_bundle_digest)" ] && [ "$(field "$TMP/one" canonical_model_digest)" != "$(field "$TMP/policy-receipt" canonical_model_digest)" ] && ok 'policy-relevant canonical data changes both bundle and model receipts' || no 'policy-relevant drift was not bound'
cp -a "$TMP/integrated" "$TMP/reordered"; mv "$TMP/reordered/rows/source" "$TMP/reordered/rows/zzz"; mv "$TMP/reordered/rows/default" "$TMP/reordered/rows/aaa"; mv "$TMP/reordered/bindings/unit" "$TMP/reordered/bindings/binding-renamed"; "$TMP/gate" verify-integrated "$TMP/reordered" "$TMP/reordered-receipt" && [ "$(field "$TMP/one" canonical_model_bytes)" = "$(field "$TMP/reordered-receipt" canonical_model_bytes)" ] && [ "$(field "$TMP/one" canonical_model_digest)" = "$(field "$TMP/reordered-receipt" canonical_model_digest)" ] && ok 'canonical model ignores record directory names and enumeration order' || no 'directory names or enumeration changed canonical model'
for kind in missing-binding missing-fact missing-attestation duplicate-id incomplete-binding; do cp -a "$TMP/integrated" "$TMP/$kind"; case "$kind" in missing-binding) rm -rf "$TMP/$kind/bindings/unit";; missing-fact) rm -rf "$TMP/$kind/facts/declaration";; missing-attestation) rm -rf "$TMP/$kind/attestations/000";; duplicate-id) cp -a "$TMP/$kind/bindings/unit" "$TMP/$kind/bindings/duplicate";; incomplete-binding) rm -f "$TMP/$kind/bindings/unit/signature-coverage";; esac; ! reject "$TMP/gate" verify-integrated "$TMP/$kind" "$TMP/$kind-receipt" && [ ! -e "$TMP/$kind-receipt" ] && ok "$kind model input rejects without receipt" || no "$kind model input was accepted"; done
cp -a "$TMP/integrated" "$TMP/scalar-data"; put "$TMP/scalar-data/rows/source/confirmation-answer" 'yaml: [data]; $(touch never) | multiline-like'; rccf_rebuild_confirmation "$TMP/scalar-data"; "$TMP/gate" verify-integrated "$TMP/scalar-data" "$TMP/scalar-data-receipt" && model "$TMP/scalar-data-receipt" | grep -Fq 'yaml: [data]; $(touch never) | multiline-like' && [ ! -e "$TMP/never" ] && ok 'delimiter YAML and shell-like scalar remains unambiguous data' || no 'delimiter scalar was executed or ambiguous'
cp -a "$TMP/integrated" "$TMP/nul"; printf 'nul\000\n' > "$TMP/nul/rows/source/confirmation-answer"; ! reject "$TMP/gate" verify-integrated "$TMP/nul" "$TMP/nul-receipt" && ok 'NUL scalar rejects without receipt' || no 'NUL scalar was accepted'
cp -a "$TMP/integrated" "$TMP/source"; printf drift >> "$(rccf_get "$TMP/source/root")/AGENTS.md"; ! reject "$TMP/gate" verify-integrated "$TMP/source" "$TMP/source-receipt" && [ ! -e "$TMP/source-receipt" ] && ok 'source input rejects without receipt' || no 'source input was accepted'
[ ! -e "$TMP/candidate-ran" ] && ok 'candidate data never executes' || no 'candidate data executed'
printf '\n%d passed, %d failed\n' "$PASS" "$FAIL"; [ "$FAIL" -eq 0 ]
